[project]
authors = ["Philipp Grosenick <philipp.grosenick@gt-arc.com>"]
channels = ["conda-forge"]
name = "YOLOPX-ONNX"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12"

[dependencies]
pytorch-gpu = "*"
torchvision = ">=0.21.0,<0.22"
onnxruntime = ">=1.20.1,<2"
matplotlib = ">=3.10.1,<4"
loguru = ">=0.7.2,<0.8"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
scipy = ">=1.4.1"
tqdm = ">=4.67.1, <5"
yacs = ">=0.1.8, <0.2"
cython = ">=3.0.12, <4"
matplotlib = ">=3.2.2"
numpy = ">=1.18.5"
opencv-python = ">=4.1.2"
pillow = "*"
pyyaml = ">=5.3"
tensorboardx = ">=2.6.2.2, <3"
seaborn = ">=0.13.2, <0.14"
imageio = ">=2.37.0, <3"
scikit-learn = ">=1.6.1, <2"
albumentations = ">=2.0.5, <3"
ptflops = ">=0.7.4, <0.8"
prefetch-generator = ">=1.0.3, <2"
pretrainedmodels = ">=0.7.4, <0.8"
h5py = ">=3.13.0, <4"
onnxscript = ">=0.2.2, <0.3"
